PORT_CATEGORIES = [
    "Web",
    "Remote Access",
    "Email",
    "Infrastructure",
    "Database",
    "File Sharing",
    "Security",
    "Monitoring"
]

IMPORTANT_PORTS = [
    {"port": 20, "service": "FTP Data", "protocol": "TCP", "category": "File Sharing", "description": "FTP data transfer channel."},
    {"port": 21, "service": "FTP Control", "protocol": "TCP", "category": "File Sharing", "description": "FTP command and control channel."},
    {"port": 22, "service": "SSH", "protocol": "TCP", "category": "Remote Access", "description": "Secure remote administration and tunneling."},
    {"port": 23, "service": "Telnet", "protocol": "TCP", "category": "Remote Access", "description": "Legacy insecure remote login service."},
    {"port": 25, "service": "SMTP", "protocol": "TCP", "category": "Email", "description": "Mail transfer between servers."},
    {"port": 53, "service": "DNS", "protocol": "TCP/UDP", "category": "Infrastructure", "description": "Domain name resolution service."},
    {"port": 67, "service": "DHCP Server", "protocol": "UDP", "category": "Infrastructure", "description": "Assigns IP addresses to clients."},
    {"port": 68, "service": "DHCP Client", "protocol": "UDP", "category": "Infrastructure", "description": "Receives DHCP configuration from server."},
    {"port": 69, "service": "TFTP", "protocol": "UDP", "category": "File Sharing", "description": "Simple file transfer, often used in boot environments."},
    {"port": 80, "service": "HTTP", "protocol": "TCP", "category": "Web", "description": "Standard web traffic."},
    {"port": 110, "service": "POP3", "protocol": "TCP", "category": "Email", "description": "Downloads email from mail server."},
    {"port": 123, "service": "NTP", "protocol": "UDP", "category": "Infrastructure", "description": "Time synchronization service."},
    {"port": 135, "service": "MS RPC", "protocol": "TCP", "category": "Infrastructure", "description": "Microsoft remote procedure call endpoint mapper."},
    {"port": 137, "service": "NetBIOS Name", "protocol": "UDP", "category": "File Sharing", "description": "NetBIOS name service."},
    {"port": 138, "service": "NetBIOS Datagram", "protocol": "UDP", "category": "File Sharing", "description": "NetBIOS datagram service."},
    {"port": 139, "service": "NetBIOS Session", "protocol": "TCP", "category": "File Sharing", "description": "Windows file and printer sharing legacy session."},
    {"port": 143, "service": "IMAP", "protocol": "TCP", "category": "Email", "description": "Mail access and synchronization service."},
    {"port": 161, "service": "SNMP", "protocol": "UDP", "category": "Monitoring", "description": "Network device monitoring and management."},
    {"port": 389, "service": "LDAP", "protocol": "TCP/UDP", "category": "Infrastructure", "description": "Directory services and identity lookups."},
    {"port": 443, "service": "HTTPS", "protocol": "TCP", "category": "Web", "description": "Encrypted web traffic over TLS."},
    {"port": 445, "service": "SMB", "protocol": "TCP", "category": "File Sharing", "description": "Windows file sharing and related services."},
    {"port": 465, "service": "SMTPS", "protocol": "TCP", "category": "Email", "description": "Secure SMTP over TLS."},
    {"port": 514, "service": "Syslog", "protocol": "UDP", "category": "Monitoring", "description": "Event and log forwarding service."},
    {"port": 587, "service": "SMTP Submission", "protocol": "TCP", "category": "Email", "description": "Mail submission from clients to servers."},
    {"port": 636, "service": "LDAPS", "protocol": "TCP", "category": "Security", "description": "Secure LDAP over TLS."},
    {"port": 993, "service": "IMAPS", "protocol": "TCP", "category": "Email", "description": "Secure IMAP over TLS."},
    {"port": 995, "service": "POP3S", "protocol": "TCP", "category": "Email", "description": "Secure POP3 over TLS."},
    {"port": 1433, "service": "MSSQL", "protocol": "TCP", "category": "Database", "description": "Microsoft SQL Server database traffic."},
    {"port": 1521, "service": "Oracle DB", "protocol": "TCP", "category": "Database", "description": "Oracle database listener."},
    {"port": 3306, "service": "MySQL", "protocol": "TCP", "category": "Database", "description": "MySQL database connections."},
    {"port": 3389, "service": "RDP", "protocol": "TCP", "category": "Remote Access", "description": "Windows Remote Desktop."},
    {"port": 5432, "service": "PostgreSQL", "protocol": "TCP", "category": "Database", "description": "PostgreSQL database service."},
    {"port": 5900, "service": "VNC", "protocol": "TCP", "category": "Remote Access", "description": "Remote graphical desktop sharing."},
    {"port": 6379, "service": "Redis", "protocol": "TCP", "category": "Database", "description": "In-memory key-value data store."},
    {"port": 8080, "service": "HTTP Alt", "protocol": "TCP", "category": "Web", "description": "Alternative HTTP web application port."},
    {"port": 8443, "service": "HTTPS Alt", "protocol": "TCP", "category": "Web", "description": "Alternative HTTPS management and app traffic."},
    {"port": 9200, "service": "Elasticsearch", "protocol": "TCP", "category": "Database", "description": "Search and analytics API endpoint."},
    {"port": 27017, "service": "MongoDB", "protocol": "TCP", "category": "Database", "description": "MongoDB document database service."}
]